-- ============================================================
-- RESPALDO de tablas eliminadas para alinear la BD al MVP (7 tablas)
-- Fecha: 2026-07-22
-- Ambas estaban VACÍAS (0 registros) y no las usaba el código.
-- Este archivo permite recrearlas si algún día se necesitan.
-- ============================================================

-- 1) interventions (tabla de dominio extra, fuera del MVP) -----
CREATE TABLE interventions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id  UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    description TEXT NOT NULL,
    result      VARCHAR DEFAULT 'pending',
    notes       TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE interventions ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER trg_interventions_updated BEFORE UPDATE ON interventions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2) schema_migrations (plomería del sistema de migraciones) ----
CREATE TABLE schema_migrations (
    id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT NOT NULL,
    applied_at  TIMESTAMPTZ DEFAULT NOW()
);
